"use client";
import { FormEvent,useEffect,useRef,useState } from "react";
type Message={id:string;sender:string;senderName:string;text:string;createdAt:number};
type Session={conversationId:string;token:string;name:string};
const KEY="huy-live-chat-v1";
export default function LiveSupportChat({online,onActiveChange}:{online:boolean;onActiveChange:(active:boolean)=>void}){
 const [open,setOpen]=useState(false),[session,setSession]=useState<Session|null>(null),[messages,setMessages]=useState<Message[]>([]),[name,setName]=useState(""),[phone,setPhone]=useState(""),[text,setText]=useState(""),[error,setError]=useState(""),[sending,setSending]=useState(false);const list=useRef<HTMLDivElement>(null);
 useEffect(()=>{const timer=window.setTimeout(()=>{try{const saved=JSON.parse(localStorage.getItem(KEY)||"null");if(saved?.conversationId&&saved?.token)setSession(saved);}catch{localStorage.removeItem(KEY)}},0);return()=>window.clearTimeout(timer)},[]);
 useEffect(()=>{onActiveChange(open);},[open,onActiveChange]);
 useEffect(()=>{if(!open||!session)return;let active=true;const load=async()=>{try{const r=await fetch(`/api/live-chat?conversationId=${encodeURIComponent(session.conversationId)}&token=${encodeURIComponent(session.token)}`,{cache:"no-store"});if(r.ok){const d=await r.json();if(active)setMessages(current=>JSON.stringify(current)===JSON.stringify(d.messages||[])?current:(d.messages||[]));}}catch{}};void load();const timer=setInterval(load,3000);return()=>{active=false;clearInterval(timer)}},[open,session]);
 useEffect(()=>{list.current?.scrollTo({top:list.current.scrollHeight,behavior:"smooth"})},[messages]);
 async function start(e:FormEvent){e.preventDefault();setSending(true);setError("");const r=await fetch("/api/live-chat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"start",name,phone})});const d=await r.json();setSending(false);if(!r.ok){setError(d.message);return}const next={conversationId:d.id,token:d.token,name};localStorage.setItem(KEY,JSON.stringify(next));setSession(next);}
 async function send(e:FormEvent){e.preventDefault();if(!session||!text.trim())return;const value=text.trim();setText("");setSending(true);const r=await fetch("/api/live-chat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...session,text:value})});setSending(false);if(!r.ok)setText(value);}
 if(!open)return <button className={`live-consult-bubble ${online?"is-online":"is-offline"}`} type="button" onClick={()=>setOpen(true)}><span className="live-consult-icon">✦</span><span><strong>Chat trực tiếp với nhân viên</strong><small><i />{online?"Đang online · 08:00–22:00":"Ngoài giờ · Bạn vẫn có thể để lời nhắn"}</small></span><b>›</b></button>;
 return <section className="live-chat-panel" role="dialog" aria-label="Chat trực tiếp với nhân viên">
  <header><div><strong>Tư vấn trực tiếp</strong><span><i />{online?"Nhân viên đang online":"Ngoài giờ hỗ trợ"}</span></div><button onClick={()=>setOpen(false)} aria-label="Đóng">×</button></header>
  {!session?<form className="live-chat-register" onSubmit={start}><div className="live-chat-welcome"><b>Xin chào 👋</b><p>Vui lòng để lại thông tin để nhân viên Huy Apple hỗ trợ bạn.</p></div><label>Họ và tên<input value={name} onChange={e=>setName(e.target.value)} placeholder="Nguyễn Văn An" required minLength={2}/></label><label>Số điện thoại<input value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,"").slice(0,11))} placeholder="09xxxxxxxx" inputMode="tel" required/></label>{error&&<p className="live-chat-error">{error}</p>}<button disabled={sending}>{sending?"Đang kết nối...":"Bắt đầu trò chuyện"}</button><small>Thông tin chỉ được dùng để tư vấn và liên hệ về nhu cầu của bạn.</small></form>:
  <><div className="live-chat-customer"><span>Đang tư vấn cho</span><strong>{session.name}</strong></div><div className="live-chat-messages" ref={list}>{messages.filter(m=>m.sender!=="system").map(m=><article key={m.id} className={`is-${m.sender}`}><small>{m.sender==="admin"?m.senderName:"Bạn"}</small><p>{m.text}</p><time>{new Date(m.createdAt).toLocaleTimeString("vi-VN",{hour:"2-digit",minute:"2-digit"})}</time></article>)}{!messages.some(m=>m.sender==="admin")&&<div className="live-chat-waiting">Đã gửi yêu cầu. Nhân viên sẽ phản hồi ngay khi nhận được.</div>}</div><form className="live-chat-composer" onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Nhập tin nhắn..." maxLength={500}/><button disabled={sending||!text.trim()}>↑</button></form></>}
 </section>;
}
