import type { Product, ProductColor, ProductVariant } from "./products";

type PricedStorage = { storage: string; price: string; ram?: string };
type ColorAsset = ProductColor & { image: string };

function macVariants(slug: string, configurations: PricedStorage[], colors: ColorAsset[]): ProductVariant[] {
  return configurations.flatMap((configuration) => colors.map((color) => ({
    id: `${slug}-${configuration.ram}-${configuration.storage}-${color.name}`.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
    name: [configuration.ram, configuration.storage, color.name].filter(Boolean).join(" / "),
    ram: configuration.ram,
    storage: configuration.storage,
    color: color.name,
    colorHex: color.hex,
    price: configuration.price,
    stock: 10,
    image: color.image,
  })));
}

function ipadVariants(slug: string, configurations: PricedStorage[], colors: ColorAsset[]): ProductVariant[] {
  return configurations.flatMap((configuration) => colors.map((color) => ({
    id: `${slug}-${configuration.storage}-${color.name}`.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
    name: `${configuration.storage} / ${color.name}`,
    storage: configuration.storage,
    color: color.name,
    colorHex: color.hex,
    price: configuration.price,
    stock: 10,
    image: color.image,
  })));
}

const neoColors: ColorAsset[] = [
  { name: "Xanh Indigo", hex: "#33496f", image: "/products/apple/macbook-neo/indigo.jpg" },
  { name: "Hồng Phớt", hex: "#e6b7b4", image: "/products/apple/macbook-neo/blush.jpg" },
  { name: "Bạc", hex: "#d8d8d4", image: "/products/apple/macbook-neo/silver.jpg" },
  { name: "Vàng Citrus", hex: "#e7d16c", image: "/products/apple/macbook-neo/citrus.jpg" },
];

const airColors: ColorAsset[] = [
  { name: "Xanh Da Trời", hex: "#a9c6d6", image: "/products/apple/macbook-air/sky-blue.jpg" },
  { name: "Bạc", hex: "#d7d8d8", image: "/products/apple/macbook-air/silver.jpg" },
  { name: "Ánh Sao", hex: "#e6dfd0", image: "/products/apple/macbook-air/starlight.jpg" },
  { name: "Đêm Xanh Thẳm", hex: "#2d3640", image: "/products/apple/macbook-air/midnight.jpg" },
];

const proColors: ColorAsset[] = [
  { name: "Đen Không Gian", hex: "#272729", image: "/products/apple/macbook-pro/space-black.jpg" },
  { name: "Bạc", hex: "#d6d7d8", image: "/products/apple/macbook-pro/silver.jpg" },
];

const ipadProColors: ColorAsset[] = [
  { name: "Đen Không Gian", hex: "#272729", image: "/products/apple/ipad-pro/space-black.jpg" },
  { name: "Bạc", hex: "#d6d7d8", image: "/products/apple/ipad-pro/silver.jpg" },
];

const ipadAirColors: ColorAsset[] = [
  { name: "Xám Không Gian", hex: "#68696d", image: "/products/apple/ipad-air/space-gray.jpg" },
  { name: "Xanh Dương", hex: "#8094b4", image: "/products/apple/ipad-air/blue.jpg" },
  { name: "Tím", hex: "#a8a2b7", image: "/products/apple/ipad-air/purple.jpg" },
  { name: "Ánh Sao", hex: "#ded6c7", image: "/products/apple/ipad-air/starlight.jpg" },
];

const ipadColors: ColorAsset[] = [
  { name: "Xanh Dương", hex: "#7da6bc", image: "/products/apple/ipad-a16/blue.jpg" },
  { name: "Hồng", hex: "#d7a2a9", image: "/products/apple/ipad-a16/pink.jpg" },
  { name: "Vàng", hex: "#e3d36d", image: "/products/apple/ipad-a16/yellow.jpg" },
  { name: "Bạc", hex: "#d8d9db", image: "/products/apple/ipad-a16/silver.jpg" },
];

const macAirConfigurations: PricedStorage[] = [
  { ram: "16GB", storage: "512GB", price: "35.999.000đ" },
  { ram: "16GB", storage: "1TB", price: "41.999.000đ" },
  { ram: "24GB", storage: "1TB", price: "47.999.000đ" },
  { ram: "32GB", storage: "2TB", price: "63.999.000đ" },
];

const ipadPro11Configurations: PricedStorage[] = [
  { storage: "256GB", price: "33.490.000đ" },
  { storage: "512GB", price: "39.990.000đ" },
  { storage: "1TB", price: "51.990.000đ" },
  { storage: "2TB", price: "62.990.000đ" },
];

export const appleComputerProducts: Product[] = [
  {
    slug: "macbook-neo-a18-pro",
    name: "MacBook Neo",
    brand: "Apple",
    category: "macbook",
    image: neoColors[0].image,
    images: [...neoColors.map((color) => color.image), "/products/apple/macbook-neo/apple-hero.jpg"],
    badge: "Mới",
    tagline: "MacBook gọn nhẹ với chip A18 Pro, pin cả ngày và bốn màu trẻ trung.",
    description: "MacBook Neo là lựa chọn dễ tiếp cận cho học tập, công việc văn phòng và sáng tạo hằng ngày trong hệ sinh thái Apple.",
    price: "Từ 19.499.000đ",
    sellingPrice: "19.499.000đ",
    colors: neoColors.map((color) => color.hex),
    colorOptions: neoColors,
    storageOptions: ["256GB", "512GB"],
    variants: macVariants("macbook-neo-a18-pro", [
      { ram: "8GB", storage: "256GB", price: "19.499.000đ" },
      { ram: "8GB", storage: "512GB", price: "24.499.000đ" },
    ], neoColors),
    specs: ["Chip Apple A18 Pro", "CPU 6 lõi và GPU 5 lõi", "RAM hợp nhất 8GB", "Màn hình Liquid Retina 13 inch", "Camera 12MP Center Stage", "Hai cổng USB-C và MagSafe", "Touch ID", "Thời lượng pin lên đến 16 giờ", "Hệ điều hành macOS"],
    mediaLinks: [{ label: "Khám phá MacBook Neo trên Apple", url: "https://www.apple.com/vn/macbook-neo/" }],
    featured: true,
    active: true,
    source: "https://www.apple.com/vn/macbook-neo/specs/",
  },
  {
    slug: "macbook-air-13-m5",
    name: "MacBook Air 13 inch M5",
    brand: "Apple",
    category: "macbook",
    image: airColors[0].image,
    images: [...airColors.map((color) => color.image), "/products/apple/macbook-air/apple-hero.png", "/products/apple/macbook-air/apple-display.jpg"],
    badge: "M5",
    tagline: "Thiết kế siêu mỏng, chip M5 mạnh mẽ và thời lượng pin lên đến 18 giờ.",
    description: "MacBook Air 13 inch M5 cân bằng giữa tính di động, hiệu năng và thời lượng pin cho học tập, văn phòng và chỉnh sửa nội dung.",
    price: "Từ 35.999.000đ",
    sellingPrice: "35.999.000đ",
    colors: airColors.map((color) => color.hex),
    colorOptions: airColors,
    storageOptions: ["512GB", "1TB", "2TB"],
    variants: macVariants("macbook-air-13-m5", macAirConfigurations, airColors),
    specs: ["Chip Apple M5", "CPU 10 lõi và GPU lên đến 10 lõi", "RAM hợp nhất từ 16GB đến 32GB", "Màn hình Liquid Retina 13,6 inch", "Độ sáng 500 nit và hỗ trợ 1 tỷ màu", "Camera 12MP Center Stage", "MagSafe 3 và hai cổng Thunderbolt 4", "Hỗ trợ tối đa hai màn hình ngoài", "Thời lượng pin lên đến 18 giờ", "Hệ điều hành macOS"],
    mediaLinks: [{ label: "Xem hình ảnh và tính năng từ Apple", url: "https://www.apple.com/vn/macbook-air/" }],
    featured: true,
    active: true,
    source: "https://www.apple.com/vn/macbook-air/specs/",
  },
  {
    slug: "macbook-air-15-m5",
    name: "MacBook Air 15 inch M5",
    brand: "Apple",
    category: "macbook",
    image: airColors[1].image,
    images: [...airColors.map((color) => color.image), "/products/apple/macbook-air/apple-hero.png", "/products/apple/macbook-air/apple-display.jpg"],
    badge: "M5",
    tagline: "Không gian hiển thị rộng 15,3 inch trong thân máy Air mỏng và nhẹ.",
    description: "MacBook Air 15 inch M5 dành cho người cần màn hình lớn hơn nhưng vẫn ưu tiên thiết kế mỏng nhẹ và pin lâu.",
    price: "Từ 41.999.000đ",
    sellingPrice: "41.999.000đ",
    colors: airColors.map((color) => color.hex),
    colorOptions: airColors,
    storageOptions: ["512GB", "1TB", "2TB"],
    variants: macVariants("macbook-air-15-m5", macAirConfigurations.map((item) => ({ ...item, price: `${Number(item.price.replace(/\D/g, "")) + 6000000}`.replace(/\B(?=(\d{3})+(?!\d))/g, ".") + "đ" })), airColors),
    specs: ["Chip Apple M5", "CPU 10 lõi và GPU lên đến 10 lõi", "RAM hợp nhất từ 16GB đến 32GB", "Màn hình Liquid Retina 15,3 inch", "Độ sáng 500 nit và hỗ trợ 1 tỷ màu", "Hệ thống âm thanh sáu loa", "Camera 12MP Center Stage", "MagSafe 3 và hai cổng Thunderbolt 4", "Thời lượng pin lên đến 18 giờ", "Hệ điều hành macOS"],
    mediaLinks: [{ label: "Xem hình ảnh và tính năng từ Apple", url: "https://www.apple.com/vn/macbook-air/" }],
    active: true,
    source: "https://www.apple.com/vn/macbook-air/specs/",
  },
  {
    slug: "macbook-pro-14-m5",
    name: "MacBook Pro 14 inch M5",
    brand: "Apple",
    category: "macbook",
    image: proColors[0].image,
    images: [...proColors.map((color) => color.image), "/products/apple/macbook-pro/apple-display.jpg", "/products/apple/macbook-pro/apple-performance.jpg"],
    badge: "Pro",
    tagline: "Hiệu năng M5 chuyên nghiệp cùng màn hình Liquid Retina XDR 14,2 inch.",
    description: "MacBook Pro 14 inch M5 phù hợp lập trình, thiết kế, dựng phim và các quy trình sáng tạo cần hiệu năng bền bỉ.",
    price: "Từ 54.999.000đ",
    sellingPrice: "54.999.000đ",
    colors: proColors.map((color) => color.hex),
    colorOptions: proColors,
    storageOptions: ["1TB"],
    variants: macVariants("macbook-pro-14-m5", [
      { ram: "16GB", storage: "1TB", price: "54.999.000đ" },
      { ram: "24GB", storage: "1TB", price: "64.999.000đ" },
      { ram: "32GB", storage: "1TB", price: "74.999.000đ" },
    ], proColors),
    specs: ["Chip Apple M5", "CPU 10 lõi và GPU 10 lõi", "RAM hợp nhất từ 16GB đến 32GB", "Màn hình Liquid Retina XDR 14,2 inch", "ProMotion lên đến 120Hz", "Ba cổng Thunderbolt 4, HDMI và khe thẻ SDXC", "Camera 12MP Center Stage", "Hệ thống âm thanh sáu loa", "Thời lượng pin lên đến 24 giờ", "Hệ điều hành macOS"],
    mediaLinks: [{ label: "Khám phá MacBook Pro trên Apple", url: "https://www.apple.com/vn/macbook-pro/" }],
    featured: true,
    active: true,
    source: "https://www.apple.com/vn/macbook-pro/specs/",
  },
  {
    slug: "macbook-pro-16-m5-pro",
    name: "MacBook Pro 16 inch M5 Pro",
    brand: "Apple",
    category: "macbook",
    image: proColors[1].image,
    images: [...proColors.map((color) => color.image), "/products/apple/macbook-pro/apple-display.jpg", "/products/apple/macbook-pro/apple-performance.jpg"],
    badge: "M5 Pro",
    tagline: "Màn hình XDR 16,2 inch và hiệu năng M5 Pro cho khối lượng công việc lớn.",
    description: "MacBook Pro 16 inch M5 Pro là máy trạm di động cho dựng phim, đồ họa, âm thanh và phát triển phần mềm chuyên sâu.",
    price: "Từ 79.999.000đ",
    sellingPrice: "79.999.000đ",
    colors: proColors.map((color) => color.hex),
    colorOptions: proColors,
    storageOptions: ["1TB", "2TB"],
    variants: macVariants("macbook-pro-16-m5-pro", [
      { ram: "24GB", storage: "1TB", price: "79.999.000đ" },
      { ram: "48GB", storage: "1TB", price: "94.999.000đ" },
      { ram: "48GB", storage: "2TB", price: "105.999.000đ" },
    ], proColors),
    specs: ["Chip Apple M5 Pro", "CPU và GPU hiệu năng cao cho công việc chuyên nghiệp", "RAM hợp nhất từ 24GB đến 48GB", "Màn hình Liquid Retina XDR 16,2 inch", "ProMotion lên đến 120Hz", "Ba cổng Thunderbolt 5, HDMI và khe thẻ SDXC", "Camera 12MP Center Stage", "Hệ thống âm thanh sáu loa", "Thời lượng pin cả ngày", "Hệ điều hành macOS"],
    mediaLinks: [{ label: "Khám phá MacBook Pro trên Apple", url: "https://www.apple.com/vn/macbook-pro/" }],
    active: true,
    source: "https://www.apple.com/vn/macbook-pro/specs/",
  },
  {
    slug: "ipad-pro-11-m5",
    name: "iPad Pro 11 inch M5",
    brand: "Apple",
    category: "ipad",
    image: ipadProColors[0].image,
    images: [...ipadProColors.map((color) => color.image), "/products/apple/ipad-pro/apple-hero.jpg", "/products/apple/ipad-pro/apple-display.jpg"],
    badge: "M5",
    tagline: "iPad Pro siêu mỏng với chip M5 và màn hình Ultra Retina XDR 11 inch.",
    description: "iPad Pro 11 inch M5 kết hợp hiệu năng cấp máy tính với thiết kế linh hoạt cho sáng tạo, làm việc và giải trí.",
    price: "Từ 33.490.000đ",
    sellingPrice: "33.490.000đ",
    colors: ipadProColors.map((color) => color.hex),
    colorOptions: ipadProColors,
    storageOptions: ipadPro11Configurations.map((item) => item.storage),
    variants: ipadVariants("ipad-pro-11-m5", ipadPro11Configurations, ipadProColors),
    specs: ["Chip Apple M5", "Màn hình Ultra Retina XDR 11 inch", "Công nghệ OLED hai lớp", "ProMotion 10Hz đến 120Hz", "Camera trước 12MP Center Stage ngang", "Camera sau góc rộng 12MP", "Hỗ trợ Apple Pencil Pro", "Cổng Thunderbolt / USB 4", "Face ID", "Hỗ trợ Wi-Fi 7"],
    mediaLinks: [{ label: "Xem iPad Pro trên Apple", url: "https://www.apple.com/vn/ipad-pro/" }],
    featured: true,
    active: true,
    source: "https://www.apple.com/vn/ipad-pro/specs/",
  },
  {
    slug: "ipad-pro-13-m5",
    name: "iPad Pro 13 inch M5",
    brand: "Apple",
    category: "ipad",
    image: ipadProColors[1].image,
    images: [...ipadProColors.map((color) => color.image), "/products/apple/ipad-pro/apple-hero.jpg", "/products/apple/ipad-pro/apple-display.jpg"],
    badge: "M5",
    tagline: "Không gian sáng tạo 13 inch, màn hình Ultra Retina XDR và chip M5.",
    description: "iPad Pro 13 inch M5 cung cấp màn hình lớn cho hội họa, dựng video, thiết kế và đa nhiệm chuyên nghiệp.",
    price: "Từ 44.990.000đ",
    sellingPrice: "44.990.000đ",
    colors: ipadProColors.map((color) => color.hex),
    colorOptions: ipadProColors,
    storageOptions: ["256GB", "512GB", "1TB", "2TB"],
    variants: ipadVariants("ipad-pro-13-m5", [
      { storage: "256GB", price: "44.990.000đ" }, { storage: "512GB", price: "51.490.000đ" },
      { storage: "1TB", price: "62.990.000đ" }, { storage: "2TB", price: "73.590.000đ" },
    ], ipadProColors),
    specs: ["Chip Apple M5", "Màn hình Ultra Retina XDR 13 inch", "Công nghệ OLED hai lớp", "ProMotion 10Hz đến 120Hz", "Camera trước 12MP Center Stage ngang", "Camera sau góc rộng 12MP", "Hỗ trợ Apple Pencil Pro", "Cổng Thunderbolt / USB 4", "Face ID", "Hỗ trợ Wi-Fi 7"],
    mediaLinks: [{ label: "Xem iPad Pro trên Apple", url: "https://www.apple.com/vn/ipad-pro/" }],
    active: true,
    source: "https://www.apple.com/vn/ipad-pro/specs/",
  },
  {
    slug: "ipad-air-11-m4",
    name: "iPad Air 11 inch M4",
    brand: "Apple",
    category: "ipad",
    image: ipadAirColors[1].image,
    images: [...ipadAirColors.map((color) => color.image), "/products/apple/ipad-air/apple-hero.png"],
    badge: "M4",
    tagline: "Chip M4 mạnh mẽ trong thiết kế Air mỏng nhẹ với bốn màu sắc.",
    description: "iPad Air 11 inch M4 là lựa chọn linh hoạt cho học tập, ghi chú, thiết kế và làm việc di động.",
    price: "Từ 16.689.000đ",
    sellingPrice: "16.689.000đ",
    colors: ipadAirColors.map((color) => color.hex),
    colorOptions: ipadAirColors,
    storageOptions: ["128GB", "256GB", "512GB", "1TB"],
    variants: ipadVariants("ipad-air-11-m4", [
      { storage: "128GB", price: "16.689.000đ" }, { storage: "256GB", price: "19.489.000đ" },
      { storage: "512GB", price: "25.089.000đ" }, { storage: "1TB", price: "30.689.000đ" },
    ], ipadAirColors),
    specs: ["Chip Apple M4", "Màn hình Liquid Retina 11 inch", "Dải màu rộng P3 và True Tone", "Camera trước 12MP Center Stage ngang", "Camera sau góc rộng 12MP", "Hỗ trợ Apple Pencil Pro", "Touch ID trên nút nguồn", "Cổng USB-C", "Hỗ trợ Wi-Fi 7", "Thời lượng pin cả ngày"],
    mediaLinks: [{ label: "Xem iPad Air trên Apple", url: "https://www.apple.com/vn/ipad-air/" }],
    featured: true,
    active: true,
    source: "https://www.apple.com/vn/ipad-air/specs/",
  },
  {
    slug: "ipad-air-13-m4",
    name: "iPad Air 13 inch M4",
    brand: "Apple",
    category: "ipad",
    image: ipadAirColors[3].image,
    images: [...ipadAirColors.map((color) => color.image), "/products/apple/ipad-air/apple-hero.png"],
    badge: "M4",
    tagline: "Màn hình Liquid Retina 13 inch rộng rãi cùng hiệu năng Apple M4.",
    description: "iPad Air 13 inch M4 dành cho người cần không gian hiển thị lớn hơn để đa nhiệm, sáng tạo và giải trí.",
    price: "Từ 22.089.000đ",
    sellingPrice: "22.089.000đ",
    colors: ipadAirColors.map((color) => color.hex),
    colorOptions: ipadAirColors,
    storageOptions: ["128GB", "256GB", "512GB", "1TB"],
    variants: ipadVariants("ipad-air-13-m4", [
      { storage: "128GB", price: "22.089.000đ" }, { storage: "256GB", price: "24.889.000đ" },
      { storage: "512GB", price: "30.489.000đ" }, { storage: "1TB", price: "36.089.000đ" },
    ], ipadAirColors),
    specs: ["Chip Apple M4", "Màn hình Liquid Retina 13 inch", "Dải màu rộng P3 và True Tone", "Camera trước 12MP Center Stage ngang", "Camera sau góc rộng 12MP", "Hỗ trợ Apple Pencil Pro", "Touch ID trên nút nguồn", "Cổng USB-C", "Hỗ trợ Wi-Fi 7", "Thời lượng pin cả ngày"],
    mediaLinks: [{ label: "Xem iPad Air trên Apple", url: "https://www.apple.com/vn/ipad-air/" }],
    active: true,
    source: "https://www.apple.com/vn/ipad-air/specs/",
  },
  {
    slug: "ipad-a16-11",
    name: "iPad 11 inch A16",
    brand: "Apple",
    category: "ipad",
    image: ipadColors[0].image,
    images: [...ipadColors.map((color) => color.image), "/products/apple/ipad-a16/apple-hero.jpg", "/products/apple/ipad-a16/apple-colors.jpg"],
    badge: "Giá tốt",
    tagline: "iPad đa năng với chip A16, màn hình 11 inch và bốn màu nổi bật.",
    description: "iPad A16 phù hợp học tập, xem nội dung, gọi video và các tác vụ hằng ngày với mức giá dễ tiếp cận.",
    price: "Từ 12.790.000đ",
    sellingPrice: "12.790.000đ",
    colors: ipadColors.map((color) => color.hex),
    colorOptions: ipadColors,
    storageOptions: ["128GB", "256GB", "512GB"],
    variants: ipadVariants("ipad-a16-11", [
      { storage: "128GB", price: "12.790.000đ" }, { storage: "256GB", price: "15.990.000đ" },
      { storage: "512GB", price: "21.490.000đ" },
    ], ipadColors),
    specs: ["Chip Apple A16", "Màn hình Liquid Retina 11 inch", "Độ phân giải 2360 x 1640 pixel", "Camera trước 12MP Center Stage ngang", "Camera sau góc rộng 12MP", "Touch ID trên nút nguồn", "Hỗ trợ Apple Pencil USB-C", "Cổng USB-C", "Hỗ trợ Wi-Fi 6", "Thời lượng pin lên đến 10 giờ"],
    mediaLinks: [{ label: "Xem iPad trên Apple", url: "https://www.apple.com/vn/ipad-11/" }],
    active: true,
    source: "https://www.apple.com/vn/ipad-11/specs/",
  },
];
