"use client";
import {FormEvent,useCallback,useEffect,useRef,useState} from "react";
type Conversation={id:string;customerName:string;phone:string;status:string;assignedAdmin:string;branchId:string;branchName:string;updatedAt:number;lastMessage:string};type Message={id:string;sender:string;senderName:string;text:string;createdAt:number};
export default function LiveChatInbox(){const [items,setItems]=useState<Conversation[]>([]),[selected,setSelected]=useState<Conversation|null>(null),[messages,setMessages]=useState<Message[]>([]),[text,setText]=useState("");const list=useRef<HTMLDivElement>(null);
 const loadList=useCallback(async()=>{const r=await fetch("/api/admin/live-chat",{cache:"no-store"});if(r.ok){const next=(await r.json()).conversations||[];setItems(current=>JSON.stringify(current)===JSON.stringify(next)?current:next)}},[]);
 const loadChat=useCallback(async(id:string)=>{const r=await fetch(`/api/admin/live-chat?conversationId=${id}`,{cache:"no-store"});if(r.ok){const d=await r.json();setSelected(current=>JSON.stringify(current)===JSON.stringify(d.conversation)?current:d.conversation);setMessages(current=>JSON.stringify(current)===JSON.stringify(d.messages||[])?current:(d.messages||[]))}},[]);
 useEffect(()=>{const first=window.setTimeout(loadList,0);const t=setInterval(loadList,3000);return()=>{clearTimeout(first);clearInterval(t)}},[loadList]);useEffect(()=>{if(!selected)return;const t=setInterval(()=>loadChat(selected.id),2500);return()=>clearInterval(t)},[selected,loadChat]);useEffect(()=>{list.current?.scrollTo({top:list.current.scrollHeight})},[messages]);
 async function send(e:FormEvent){e.preventDefault();if(!selected||!text.trim())return;const value=text;setText("");await fetch("/api/admin/live-chat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({conversationId:selected.id,text:value})});await loadChat(selected.id);await loadList()}
 async function status(value:string){if(!selected)return;await fetch("/api/admin/live-chat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"status",conversationId:selected.id,status:value})});await loadChat(selected.id);await loadList()}
 return <section className="admin-live-chat"><aside><header><strong>Cuộc trò chuyện</strong><span>{items.filter(x=>x.status!=="closed").length} đang mở</span></header><div>{items.map(x=><button key={x.id} className={selected?.id===x.id?"is-active":""} onClick={()=>loadChat(x.id)}><span className={`live-status status-${x.status}`}/><div><strong>{x.customerName}</strong><small>{x.phone}</small><em>{x.branchName||"Chưa phân chi nhánh"}</em><p>{x.lastMessage||"Đang chờ tư vấn"}</p></div><time>{new Date(x.updatedAt).toLocaleTimeString("vi-VN",{hour:"2-digit",minute:"2-digit"})}</time></button>)}{!items.length&&<p className="admin-empty-state">Chưa có khách yêu cầu tư vấn tại chi nhánh của bạn.</p>}</div></aside><main>{selected?<><header><div><strong>{selected.customerName}</strong><a href={`tel:${selected.phone}`}>{selected.phone}</a><b>{selected.branchName||"Chưa phân chi nhánh"}</b><span>{selected.assignedAdmin?`Phụ trách: ${selected.assignedAdmin}`:"Chưa có nhân viên nhận"}</span></div><select value={selected.status} onChange={e=>status(e.target.value)}><option value="waiting">Đang chờ</option><option value="active">Đang tư vấn</option><option value="closed">Đã kết thúc</option></select></header><div className="admin-live-messages" ref={list}>{messages.filter(m=>m.sender!=="system").map(m=><article key={m.id} className={`is-${m.sender}`}><small>{m.sender==="customer"?selected.customerName:m.senderName}</small><p>{m.text}</p><time>{new Date(m.createdAt).toLocaleString("vi-VN")}</time></article>)}</div><form onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} placeholder={`Tư vấn khách tại ${selected.branchName||"chi nhánh"}...`} maxLength={500}/><button className="admin-button admin-button-primary">Gửi</button></form></>:<div className="admin-live-placeholder"><b>💬</b><strong>Chọn một khách hàng</strong><span>Chỉ hội thoại thuộc chi nhánh được cấp quyền mới hiển thị.</span></div>}</main></section>}
