import { env } from "cloudflare:workers";
import { ensureAdminUserStore } from "@/db/admin-users";
type Bindings={DB:D1Database};
export type Branch={id:string;code:string;name:string;address:string;phone:string;hours:string;active:boolean;createdAt:number;staffCount:number};
const db=()=>{const value=(env as unknown as Bindings).DB;if(!value)throw new Error("Cơ sở dữ liệu chi nhánh chưa sẵn sàng.");return value};
let ready:Promise<void>|null=null;
export function ensureBranchStore(){if(!ready)ready=initialize().catch(e=>{ready=null;throw e});return ready}
async function initialize(){await db().batch([db().prepare(`CREATE TABLE IF NOT EXISTS branches (id TEXT PRIMARY KEY,code TEXT NOT NULL UNIQUE,name TEXT NOT NULL,address TEXT NOT NULL,phone TEXT NOT NULL DEFAULT '',hours TEXT NOT NULL DEFAULT '08:00–22:00',active INTEGER NOT NULL DEFAULT 1,created_at INTEGER NOT NULL)`),db().prepare("CREATE UNIQUE INDEX IF NOT EXISTS branches_code_idx ON branches(code)")]);}
const map=(r:Record<string,unknown>):Branch=>({id:String(r.id),code:String(r.code),name:String(r.name),address:String(r.address),phone:String(r.phone||""),hours:String(r.hours||"08:00–22:00"),active:Number(r.active)===1,createdAt:Number(r.created_at),staffCount:Number(r.staff_count||0)});
export async function getBranches(includeInactive=true){await Promise.all([ensureBranchStore(),ensureAdminUserStore()]);const rows=await db().prepare(`SELECT b.*,(SELECT COUNT(*) FROM admin_users u WHERE u.branch_id=b.id AND u.active=1) staff_count FROM branches b ${includeInactive?"":"WHERE b.active=1"} ORDER BY b.active DESC,b.created_at ASC`).all<Record<string,unknown>>();return rows.results.map(map)}
export async function getBranchById(id:string){await Promise.all([ensureBranchStore(),ensureAdminUserStore()]);const row=await db().prepare(`SELECT b.*,(SELECT COUNT(*) FROM admin_users u WHERE u.branch_id=b.id AND u.active=1) staff_count FROM branches b WHERE b.id=? LIMIT 1`).bind(id).first<Record<string,unknown>>();return row?map(row):undefined}
export async function createBranch(input:{code:string;name:string;address:string;phone:string;hours:string}){await ensureBranchStore();const code=input.code.trim().toUpperCase().replace(/[^A-Z0-9-]/g,"").slice(0,20),name=input.name.trim().replace(/\s+/g," ").slice(0,100),address=input.address.trim().replace(/\s+/g," ").slice(0,180),phone=input.phone.replace(/\D/g,"").slice(0,11),hours=input.hours.trim().slice(0,30)||"08:00–22:00";if(code.length<2||name.length<2||address.length<5)throw new Error("Vui lòng nhập đầy đủ mã, tên và địa chỉ chi nhánh.");const exists=await db().prepare("SELECT id FROM branches WHERE code=?").bind(code).first();if(exists)throw new Error("Mã chi nhánh đã tồn tại.");await db().prepare("INSERT INTO branches (id,code,name,address,phone,hours,active,created_at) VALUES (?,?,?,?,?,?,1,?)").bind(crypto.randomUUID(),code,name,address,phone,hours,Date.now()).run()}
export async function setBranchActive(id:string,active:boolean){await ensureBranchStore();await db().prepare("UPDATE branches SET active=? WHERE id=?").bind(active?1:0,id).run()}
