import {env} from "cloudflare:workers";import type {AdminUser} from "@/db/admin-users";import {ensureAdminUserStore} from "@/db/admin-users";import {ensureBranchStore} from "@/db/branches";
type Bindings={DB:D1Database};export type Camera={id:string;branchId:string;branchName:string;name:string;location:string;streamUrl:string;streamType:string;active:boolean;createdAt:number};export type CameraPermission={id:string;adminUserId:string;branchId:string;userName:string;branchName:string;createdAt:number};
const db=()=>{const value=(env as unknown as Bindings).DB;if(!value)throw new Error("Cơ sở dữ liệu camera chưa sẵn sàng.");return value};let ready:Promise<void>|null=null;
export function ensureCameraStore(){if(!ready)ready=initialize().catch(e=>{ready=null;throw e});return ready}async function initialize(){await Promise.all([ensureAdminUserStore(),ensureBranchStore()]);await db().batch([db().prepare(`CREATE TABLE IF NOT EXISTS branch_cameras (id TEXT PRIMARY KEY,branch_id TEXT NOT NULL,name TEXT NOT NULL,location TEXT NOT NULL DEFAULT '',stream_url TEXT NOT NULL,stream_type TEXT NOT NULL DEFAULT 'embed',active INTEGER NOT NULL DEFAULT 1,created_at INTEGER NOT NULL)`),db().prepare(`CREATE TABLE IF NOT EXISTS camera_branch_permissions (id TEXT PRIMARY KEY,admin_user_id TEXT NOT NULL,branch_id TEXT NOT NULL,created_at INTEGER NOT NULL)`),db().prepare("CREATE UNIQUE INDEX IF NOT EXISTS camera_permission_unique_idx ON camera_branch_permissions(admin_user_id,branch_id)"),db().prepare("CREATE INDEX IF NOT EXISTS branch_cameras_branch_idx ON branch_cameras(branch_id,active)")])}
const mapCamera=(r:Record<string,unknown>):Camera=>({id:String(r.id),branchId:String(r.branch_id),branchName:String(r.branch_name||""),name:String(r.name),location:String(r.location||""),streamUrl:String(r.stream_url),streamType:String(r.stream_type),active:Number(r.active)===1,createdAt:Number(r.created_at)});
export async function getAccessibleCameras(user:AdminUser){await ensureCameraStore();const query=user.role==="owner"?db().prepare(`SELECT c.*,b.name branch_name FROM branch_cameras c JOIN branches b ON b.id=c.branch_id ORDER BY b.name,c.name`):db().prepare(`SELECT c.*,b.name branch_name FROM branch_cameras c JOIN branches b ON b.id=c.branch_id JOIN camera_branch_permissions p ON p.branch_id=c.branch_id WHERE p.admin_user_id=? AND c.active=1 AND b.active=1 ORDER BY b.name,c.name`).bind(user.id);const rows=await query.all<Record<string,unknown>>();return rows.results.map(mapCamera)}
export async function getCameraPermissions(){await ensureCameraStore();const rows=await db().prepare(`SELECT p.*,u.name user_name,b.name branch_name FROM camera_branch_permissions p JOIN admin_users u ON u.id=p.admin_user_id JOIN branches b ON b.id=p.branch_id ORDER BY b.name,u.name`).all<Record<string,unknown>>();return rows.results.map(r=>({id:String(r.id),adminUserId:String(r.admin_user_id),branchId:String(r.branch_id),userName:String(r.user_name),branchName:String(r.branch_name),createdAt:Number(r.created_at)}))}
export async function createCamera(input:{branchId:string;name:string;location:string;streamUrl:string;streamType:string}){await ensureCameraStore();const name=input.name.trim().slice(0,100),location=input.location.trim().slice(0,120),streamUrl=input.streamUrl.trim().slice(0,2000),streamType=["embed","video","snapshot"].includes(input.streamType)?input.streamType:"embed";if(name.length<2||!input.branchId)throw new Error("Vui lòng chọn chi nhánh và nhập tên camera.");let url:URL;try{url=new URL(streamUrl)}catch{throw new Error("URL camera không hợp lệ.")}if(url.protocol!=="https:"&&url.protocol!=="http:")throw new Error("Camera phải sử dụng URL HTTP hoặc HTTPS.");await db().prepare("INSERT INTO branch_cameras (id,branch_id,name,location,stream_url,stream_type,active,created_at) VALUES (?,?,?,?,?,?,1,?)").bind(crypto.randomUUID(),input.branchId,name,location,streamUrl,streamType,Date.now()).run()}
export async function setCameraActive(id:string,active:boolean){await ensureCameraStore();await db().prepare("UPDATE branch_cameras SET active=? WHERE id=?").bind(active?1:0,id).run()}
export async function grantCameraBranch(adminUserId:string,branchId:string){await ensureCameraStore();await db().prepare("INSERT OR IGNORE INTO camera_branch_permissions (id,admin_user_id,branch_id,created_at) VALUES (?,?,?,?)").bind(crypto.randomUUID(),adminUserId,branchId,Date.now()).run()}
export async function revokeCameraPermission(id:string){await ensureCameraStore();await db().prepare("DELETE FROM camera_branch_permissions WHERE id=?").bind(id).run()}
