import {requireOwnerPage} from "@/app/admin-auth";import {getBranches} from "@/db/branches";import {createBranchAction,toggleBranchAction} from "./actions";
export const dynamic="force-dynamic";
export default async function BranchesPage({searchParams}:{searchParams:Promise<{error?:string;status?:string}>}){await requireOwnerPage("/admin/branches");const [branches,query]=await Promise.all([getBranches().catch(()=>[]),searchParams]);return <>
 <div className="admin-topline"><div><span>Hệ thống cửa hàng</span><h1>Quản lý chi nhánh</h1><p className="admin-subtitle">Thiết lập địa điểm kinh doanh và phân bổ đội ngũ theo từng cửa hàng.</p></div></div>
 {query.status&&<p className="admin-alert success">Đã cập nhật thông tin chi nhánh.</p>}{query.error&&<p className="admin-alert error">{query.error}</p>}
 <section className="admin-branch-summary"><article><span>Tổng chi nhánh</span><strong>{branches.length}</strong></article><article><span>Đang hoạt động</span><strong>{branches.filter(x=>x.active).length}</strong></article><article><span>Nhân sự được phân bổ</span><strong>{branches.reduce((s,x)=>s+x.staffCount,0)}</strong></article></section>
 <section className="admin-card admin-branch-create"><div className="admin-card-head"><div><span>Chi nhánh mới</span><h2>Thêm địa điểm kinh doanh</h2></div></div><form action={createBranchAction} className="admin-branch-form"><label className="admin-field"><span>Mã chi nhánh</span><input name="code" required placeholder="CN-Q1"/></label><label className="admin-field"><span>Tên chi nhánh</span><input name="name" required placeholder="Huy Apple Quận 1"/></label><label className="admin-field admin-branch-address"><span>Địa chỉ</span><input name="address" required placeholder="122/4 Cô Giang, TP.HCM"/></label><label className="admin-field"><span>Điện thoại</span><input name="phone" inputMode="tel" placeholder="02879797999"/></label><label className="admin-field"><span>Giờ hoạt động</span><input name="hours" defaultValue="08:00–22:00"/></label><button className="admin-button admin-button-primary">Thêm chi nhánh</button></form></section>
 <section className="admin-branch-grid">{branches.map(branch=><article className={`admin-branch-card ${branch.active?"":"is-inactive"}`} key={branch.id}><header><span>{branch.code}</span><i className={branch.active?"is-online":""}/></header><h2>{branch.name}</h2><p>{branch.address}</p><dl><div><dt>Điện thoại</dt><dd>{branch.phone||"Chưa cập nhật"}</dd></div><div><dt>Giờ mở cửa</dt><dd>{branch.hours}</dd></div><div><dt>Nhân sự</dt><dd>{branch.staffCount} người</dd></div></dl><footer><span className={`admin-badge ${branch.active?"status-active":"status-inactive"}`}>{branch.active?"Đang hoạt động":"Tạm ngưng"}</span><form action={toggleBranchAction}><input type="hidden" name="id" value={branch.id}/><input type="hidden" name="active" value={String(!branch.active)}/><button className="admin-button">{branch.active?"Tạm ngưng":"Mở lại"}</button></form></footer></article>)}{!branches.length&&<div className="admin-card admin-empty-state">Chưa có chi nhánh. Hãy tạo địa điểm đầu tiên phía trên.</div>}</section>
 </>}
